### PR TITLE
Filtration Systems implemented

### PR DESCRIPTION
**Pull request by Danhuth**

### CODE REVIEW

**Comment by justinnhli** [comment]
Please resolve merge conflicts first and tag us again.

**Comment by Danhuth** [comment]
@justinnhli @crzeller11

**Comment by justinnhli** [comment]
You seem to be reverting some commits on master (eg. look at `app/build.gradle`) - you need to fix that.

**Comment by Danhuth** [comment]
@justinnhli Android Studio automatically replaces "compile" with "Implementation" stating that "configuration 'compile' is obsolete and has been replaced with 'implementation'. It will be removed at the end of 2018"

**Comment by justinnhli** [comment]
@Danhuth Yes, and your changes are going the *other* way (from compile to implementation)

**Comment by Danhuth** [comment]
D'oh. Fixed.

**Comment by justinnhli** [comment]
I am not convinced that this is not overwriting other parts of Master. There are lots of weird things going on here - in `AsyncCallback.java` you still have lines from resolving merge conflicts, and you are also adding an `AsynchResult.java` (note the `h` in `Asynch`). There are a lot of other spurious permission changes that shouldn't be there. What's going on?

**Comment by Danhuth** [comment]
@justinnhli I removed the bonus asyncresult and got rid of the lines from merge conflicts. 
I don't really know what you're talking about in regard to the permission changes. Do you mean the "access network state" and "Internet" permissions?

**Comment by justinnhli** [comment]
fixed it for you. merged.

**Pull request merged**
