### PR TITLE
Finished Implementing Image/Gifs

### PR DESCRIPTION
**Pull request by wchen-oxy**
Added Picasso and Glide libraries as needed. Images and Gifs can now pull directly from online source

### CODE REVIEW

**Comment by wchen-oxy** [comment]
@justinnhli @crzeller11

**Review by crzeller11 — APPROVED** [review]
Ok because there are no additions, I don't mind approving this.

**Comment by wchen-oxy** [comment]
@crzeller11 
There actually are a couple small additions in the gradle and each respective nutrition/exercise. It's just that they're harder to find since I deleted an unnecessary jar file since I used "implementation" in the gradle.

**Comment by justinnhli** [comment]
merged. Thanks.

**Pull request merged**
