### PR TITLE
Created unit test to check if kml map url is valid

### PR DESCRIPTION
**Pull request by temucher**
@crzeller11  @justinnhli

### CODE REVIEW

**Comment by justinnhli** [comment]
This is a weird test for several reasons:

1. The URL is just a constant here, and there's no guarantee that it's the one used in the app. If you are testing this just at the URL level, you should test the real URL used by the app.
2. Just testing that it's roughly in URL format doesn't mean that it's accessible. You should instead try to read from it, or at least make sure it doesn't give a 404 error.

**Comment by temucher** [comment]
The url is the known url for one of the KML files. I will push new changes that read it.

**Comment by temucher** [comment]
@justinnhli  @crzeller11

**Comment by justinnhli** [comment]
1. Make this generic - turn it into a function that takes a String and tests it. 
2. Use `assert` instead of prints. Take a look at @crzeller11's [example](https://github.com/oxy-compsci/GetFitLA/blob/master/app/src/test/java/practicum/getfitla_v3/ExampleUnitTest.java#L15). This will make the CI test actually fail.
2. Is this URL anywhere else in the repo? It should be, right? But I can't find it. If this is for a upcoming PR, then change the URL one already in the repo (see next point).
3. One existing URL in the repo is in `Exercise.java`. Say you refactor this to a function `checkURL`, which returns true or false. You should then do:

    ```
    assert checkURL(Exercise.EXERCISE_SHEET_URL);
    ```

**Comment by temucher** [comment]
@justinnhli 
1. Where do I pass a value to the function to test it then?
2. Ok.
3. The url is slightly modified from a variable in the strings.xml file. XML won't let you have a URL with & without adding amp; after it. Looking into storing URLs in a different way.

**Comment by justinnhli** [comment]
1. As the argument? I'm not sure what your asking here

3. Is it in the XML because of translation/internationalization issues? Why is it not a constant like the exercise one?

**Comment by temucher** [comment]
1. Sorry that wasn't clear. Are you telling me to run it as a Parameterized class with a bunch of test URLs in an array to test DownloadFileURLTest()?
2. Yes it is because of translation. The phone language settings cause it to look at different URLs for the kml.

**Comment by justinnhli** [comment]
1. No, it's a test. Just call the function multiple times with different parameters.

3. Are there functions that get the string for different translations? We can use that and test both the English and Spanish links.

**Comment by temucher** [comment]
1. Ok.
2. I have a hardcoded function that I have been using to point at the correct static map files. I can probably use that.

**Comment by justinnhli** [comment]
If you're manually parsing the XML, that's probably a bad idea. Not sure if useful, but take a look at stackoverflow.com/questions/9475589/how-to-get-string-from-different-locales-in-android.

**Comment by temucher** [comment]
Not sure what you mean about manually passing the XML being a bad idea. Its not the raw xml, its a string value set in the xml file. Not sure if im being clear.

Accessing it by using some form of getString(R.string.<string_name>) seems to be standard.

**Comment by justinnhli** [comment]
Based on what we talked about, I think keeping this test (and adapting it as discussed) is still a good idea. Run it with existing urls in the repo and I'll merge it.

**Comment by temucher** [comment]
Fetching from URL is obsolete at the moment @justinnhli

**Comment by justinnhli** [comment]
If this is no longer a unit test for checking URLs, please open a new PR

**Pull request closed without merging**
